# Generated by Django 4.2.16 on 2024-09-20 13:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cronjob', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cronjob',
            name='app',
        ),
        migrations.AddField(
            model_name='cronjob',
            name='group',
            field=models.ForeignKey(default=1, help_text='Grupo ao qual este cron job pertence.', on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='cronjob.crongroup'),
            preserve_default=False,
        ),
    ]
