# Generated by Django 4.2.16 on 2024-09-20 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cronjob', '0002_remove_cronjob_app_cronjob_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('status_code', models.IntegerField()),
                ('response_time', models.FloatField()),
                ('success', models.BooleanField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('cronjob', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='cronjob.cronjob')),
            ],
        ),
    ]
