# Generated by Django 4.2.16 on 2024-09-20 21:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cronjob', '0003_requeststatistics'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requeststatistics',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddField(
            model_name='requeststatistics',
            name='app',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='request_statistics', to='cronjob.cronapp'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='requeststatistics',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
