# Generated by Django 4.2.16 on 2024-09-20 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cronjob', '0004_alter_requeststatistics_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requeststatistics',
            name='cronjob',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_statistics', to='cronjob.cronjob'),
        ),
    ]
